# Generated by Django 3.1.1 on 2020-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=90, verbose_name='Phone Number'),
        ),
    ]
